apiVersion: v1
kind: Service
metadata:
  name: pupero-database
  namespace: pupero
spec:
  selector: {app: pupero-database}
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pupero-rabbitmq
  namespace: pupero
spec:
  selector: {app: pupero-rabbitmq}
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pupero-login
  namespace: pupero
spec:
  selector: {app: pupero-login}
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pupero-offers
  namespace: pupero
spec:
  selector: {app: pupero-offers}
  ports:
    - name: http
      port: 8002
      targetPort: 8002
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pupero-transactions
  namespace: pupero
spec:
  selector: {app: pupero-transactions}
  ports:
    - name: http
      port: 8003
      targetPort: 8003
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pupero-api-manager
  namespace: pupero
spec:
  selector: {app: pupero-api-manager}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pupero-admin
  namespace: pupero
spec:
  selector: {app: pupero-admin}
  ports:
    - name: http
      port: 8010
      targetPort: 8010
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pupero-flask
  namespace: pupero
spec:
  selector: {app: pupero-flask}
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pupero-monerod
  namespace: pupero
spec:
  selector: {app: pupero-monerod}
  ports:
    - name: p2p
      port: 28080
      targetPort: 28080
    - name: rpc
      port: 28081
      targetPort: 28081
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pupero-wallet-rpc
  namespace: pupero
spec:
  selector: {app: pupero-wallet-rpc}
  ports:
    - name: rpc
      port: 18083
      targetPort: 18083
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pupero-walletmanager
  namespace: pupero
spec:
  selector: {app: pupero-walletmanager}
  ports:
    - name: http
      port: 8004
      targetPort: 8004
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pupero-matrix-db
  namespace: pupero
spec:
  selector: {app: pupero-matrix-db}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pupero-matrix-synapse
  namespace: pupero
spec:
  selector: {app: pupero-matrix-synapse}
  ports:
    - name: http
      port: 8008
      targetPort: 8008
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pupero-element
  namespace: pupero
spec:
  selector: {app: pupero-element}
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: pupero-explorer
  namespace: pupero
spec:
  selector: {app: pupero-explorer}
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
