apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pupero-v2.fullname" . }}-secrets
  labels:
    {{- include "pupero-v2.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_ROOT_PASSWORD: {{ .Values.secrets.dbRootPassword | quote }}
  DB_NAME: {{ .Values.secrets.dbName | quote }}
  RABBITMQ_USER: {{ .Values.secrets.rabbitmqUser | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitmqPassword | quote }}
  SECRET_KEY: {{ .Values.secrets.flaskSecretKey | quote }}
  MATRIX_DEFAULT_PASSWORD_SECRET: {{ .Values.secrets.matrixDefaultPasswordSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.matrix.db.password | quote }}
  WALLET_RPC_PASSWORD: {{ .Values.walletRpc.password | quote }}
